name: "Publish Package"

on:
  workflow_dispatch:
    inputs:
      publish_target:
        description: "What is The Point...?..."
        type: choice
        options:
        -
        - gpr
        - npm
        - jsr
        - page
  push:
    tags:
      - "v*"

jobs:
  build:
    if: ${{ inputs.publish_target != 'page' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Setup pnpm"
        uses: pnpm/action-setup@v4

      - name: "Setup Node"
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: "Install dependencies"
        run: pnpm install --frozen-lockfile

      - name: "Run tests"
        run: pnpm vitest run --coverage

      #: ------------------------------------
      #: Codecov

      - name: "Codecov: Run tests (report)"
        run: pnpm vitest run --reporter=junit --outputFile=test-report.junit.xml

      - name: "Codecov: Upload test results"
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: "Codecov: Upload coverage reports"
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      #: Codecov
      #: ------------------------------------

      - name: "Build"
        run: pnpm build

      - name: "Build (jsr)"
        run: pnpm build:jsr

      - name: "Upload artifact"
        uses: actions/upload-artifact@v4
        with:
          name: package-artifact
          path: |
            dist
            package.json
            LICENSE
            README.md
            node_modules
            jsr.json
            lib

  deploy:
    if: ${{ inputs.publish_target == 'page' || github.event_name == 'push' }}
    # needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Setup pnpm"
        uses: pnpm/action-setup@v4

      - name: "Setup Node"
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: "Install dependencies"
        run: pnpm install --frozen-lockfile

      - name: "Build"
        run: pnpm build

      - name: "Make demo"
        run: pnpm demo

      - name: "Setup Pages"
        uses: actions/configure-pages@v5

      - name: "Upload artifact"
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./demo"

      - name: "Deploy to GitHub Pages"
        id: deployment
        uses: actions/deploy-pages@v4

  publish-gpr:
    if: ${{ inputs.publish_target == 'gpr' || github.event_name == 'push' }}
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: "Download artifact"
        uses: actions/download-artifact@v4
        with:
          name: package-artifact

      - name: "Setup Node for GPR"
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: "https://npm.pkg.github.com"

      - name: "Publish to GitHub Packages"
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish-npm:
    if: ${{ inputs.publish_target == 'npm' || github.event_name == 'push' }}
    needs: build
    runs-on: ubuntu-latest
    permissions:
      id-token: write #: OIDC (not working)
      contents: read
    steps:
      - name: "Download artifact"
        uses: actions/download-artifact@v4
        with:
          name: package-artifact

      - name: "Setup Node for npm"
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: "https://registry.npmjs.org"
          scope: "@verikami"

      - name: "Publish to npm"
        # run: npm publish --access public
        run: npm publish --access public --provenance
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  publish-jsr:
    if: ${{ inputs.publish_target == 'jsr' || github.event_name == 'push' }}
    needs: build
    runs-on: ubuntu-latest
    permissions:
      id-token: write #: OIDC
      contents: read
    steps:
      - name: "Download artifact"
        uses: actions/download-artifact@v4
        with:
          name: package-artifact

      - name: "Publish package"
        run: npx jsr publish
